// Copyright 2026 The ARCORIS Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package snapshot provides common point-in-time read-model primitives.
//
// Snapshot[R, T] carries a value with the authoritative revision type for the
// source that produced it. R may be LocalRevision for package-managed sources,
// or it may be a domain revision such as an object-store revision or a
// capacity-vector revision. Snapshot does not clone or freeze Value; ownership
// belongs to the source that produced the snapshot. The package requires only
// that R is comparable so callers can detect changes by equality.
//
// Stamped[R, T] adds local publication time metadata to a Snapshot. Stamped
// timestamps are useful for diagnostics and freshness reporting, but they are
// not distributed clocks and do not define domain event time.
//
// LocalRevision is only for sources whose revisions are generated by this
// package, such as Store and Publisher. LocalRevision values are monotonic within
// one source only. Do not coerce external domain revisions into LocalRevision;
// use Snapshot[DomainRevision, T] or Stamped[DomainRevision, T] instead.
// Intended examples include:
//
//	snapshot.Snapshot[objectstore.Revision, objectcache.View]
//	snapshot.Snapshot[snapshot.LocalRevision, HealthState]
//
// Store is the safe mutable-value holder. It owns one always-present value,
// protects it with a mutex, isolates readers and writers with CloneFunc, and
// advances LocalRevision when the value changes. Store starts at
// LocalRevision(1) because NewStore commits the initial value. The zero-value
// Store is invalid and must not be used.
//
// Publisher is the fast immutable copy-on-write publisher. It publishes immutable
// records through an atomic pointer so readers can load the latest snapshot
// without locking or cloning. Values passed to Publisher must not be mutated
// after publication. The zero-value Publisher is usable and reports zero
// snapshots until the first publication.
//
// Source, StampedSource, and RevisionSource describe always-available sources.
// Store is always available after NewStore, and Publisher has defined zero-value
// publication semantics before its first Publish. SnapshotReader, StampedReader,
// and RevisionReader describe sources that may not be ready and need to return
// an error instead of a fabricated zero snapshot.
//
// ChangedSince methods are equality-based. This package does not define global
// revision ordering, and it does not assume revisions are dense or comparable
// across unrelated sources. It also does not implement TTL, cache policy,
// staleness decisions, background refresh, loading, watch subscriptions, history
// retention, diffing, serialization, persistence, event sourcing, or generic
// deep copy.
package snapshot
