// Copyright 2026 The ARCORIS Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package snapshot

// LocalRevision is the package-managed revision type used by Store and
// Publisher.
//
// LocalRevision is appropriate only for sources whose revisions are generated by
// this package. Values are monotonic within one Store or Publisher, but they are
// not globally meaningful and must not be compared across unrelated sources as a
// distributed ordering.
//
// Domain packages with authoritative revisions should use Snapshot[DomainRevision,
// T] or Stamped[DomainRevision, T] directly. They should not coerce those
// revisions into LocalRevision.
type LocalRevision uint64

// ZeroLocalRevision is the empty package-managed revision.
//
// ZeroLocalRevision means no committed package-managed publication. It is not a
// committed Store revision because NewStore commits its initial value at
// LocalRevision(1).
const ZeroLocalRevision LocalRevision = 0

// IsZero reports whether r is ZeroLocalRevision.
func (r LocalRevision) IsZero() bool {
	return r == ZeroLocalRevision
}

// Next returns the next package-managed local revision.
//
// Next panics on uint64 overflow. Wrapping would make an old publication look
// like the absence of a publication, so overflow is treated as a programmer
// error.
func (r LocalRevision) Next() LocalRevision {
	if r == ^LocalRevision(0) {
		panic("snapshot: local revision overflow")
	}

	return r + 1
}

// ChangedSince reports whether r differs from prev.
//
// The check is intentionally equality-based. It does not imply that local
// revisions from different sources can be ordered globally.
func (r LocalRevision) ChangedSince(prev LocalRevision) bool {
	return r != prev
}
