// Copyright 2026 The ARCORIS Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codecjson

// jsonKind identifies one private JSON node category.
type jsonKind uint8

const (
	// jsonKindInvalid is the zero sentinel for an uninitialized node.
	//
	// Production decode paths never intentionally emit this kind. Encode paths
	// treat it defensively rather than making the private node model a public
	// validation surface.
	jsonKindInvalid jsonKind = iota

	// jsonKindNull represents the JSON null literal.
	jsonKindNull

	// jsonKindBool represents the JSON true and false literals.
	jsonKindBool

	// jsonKindString represents a JSON string after UTF-8 validation.
	jsonKindString

	// jsonKindNumber represents a JSON number stored as source token text.
	jsonKindNumber

	// jsonKindArray represents a JSON array whose items remain in source order.
	jsonKindArray

	// jsonKindObject represents a JSON object whose members remain in source order.
	jsonKindObject
)

// jsonNode stores one ordered JSON value.
//
// Object and array slices are package-private and never exposed as public API.
// This keeps the node model a codec implementation detail rather than a public
// reusable JSON AST.
type jsonNode struct {
	// kind selects which payload fields are meaningful.
	kind jsonKind

	// boolValue stores JSON true/false payloads.
	boolValue bool

	// stringValue stores decoded JSON string payloads after UTF-8 validation.
	stringValue string

	// numberText stores the original JSON number token text.
	//
	// Keeping source text lets the value decoder classify integers and decimals
	// exactly, without a float64 intermediate.
	numberText string

	// items stores array elements in source order.
	items []jsonNode

	// members stores object members in source order.
	//
	// Duplicate names are rejected while decoding, so this slice represents the
	// exact member order that can be preserved by value/object conversion.
	members []jsonMember
}

// jsonMember stores one ordered JSON object member.
type jsonMember struct {
	// name is the exact JSON object member name.
	name string

	// value is the member payload.
	value jsonNode
}

// member returns the first member value with name.
//
// Duplicate names are rejected during decode and are not generated by encode
// conversion helpers, so "first" is only a defensive definition for manually
// constructed test nodes.
func (n jsonNode) member(name string) (jsonNode, bool) {
	for _, member := range n.members {
		if member.name == name {
			return member.value, true
		}
	}

	return jsonNode{}, false
}

// hasMember reports whether n contains a member named name.
func (n jsonNode) hasMember(name string) bool {
	_, ok := n.member(name)
	return ok
}
